name: Test Backend

on:
  push:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker build -t nodejs_postgres-node .

      - name: Run
        run: docker compose up -d --build